(G-code generated by FlatCAM Evo vUnstable - Version Date: 2023/6/31)

(Name: power-stage-PTH.drl_cnc)
(Type: G-code from Excellon)
(Units: MM)

(Created on Saturday, 04 April 2026 at 13:27)

(This preprocessor is the default preprocessor.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 8 -> Dia: 2.5)

(FEEDRATE Z: )
(Tool: 8 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 8 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 8 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 8 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 8 -> Z_Move: 2)

(Z Start: None mm)
(Z End: 15 mm)
(X,Y End: None mm)
(Steps per circle: 16)
(Preprocessor Excellon: default)

(X range:    2.5489 ...   68.0109  mm)
(Y range:    2.4300 ...   67.9300  mm)

(Spindle Speed: 0 RPM)
G21
G90
G94

G01 F300.00
G00 Z2.0000

M03
G00 X64.9989 Y66.6800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X3.7989 Y66.6800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X3.7989 Y3.6800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X64.9989 Y3.6800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


