(G-code generated by FlatCAM Evo vUnstable - Version Date: 2023/6/31)

(Name: controller-PTH.drl_cnc)
(Type: G-code from Excellon)
(Units: MM)

(Created on Saturday, 18 April 2026 at 17:53)

(This preprocessor is the default preprocessor.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 5 -> Dia: 1.5)

(FEEDRATE Z: )
(Tool: 5 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 5 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 5 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 5 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 5 -> Z_Move: 2)

(Z Start: None mm)
(Z End: 15 mm)
(X,Y End: None mm)
(Steps per circle: 16)
(Preprocessor Excellon: default)

(X range:    4.7410 ...  127.7500  mm)
(Y range:    3.9190 ...   71.7500  mm)

(Spindle Speed: 0 RPM)
G21
G90
G94

G01 F300.00
G00 Z2.0000

M03
G00 X16.6910 Y24.3630
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X16.6910 Y23.0630
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X5.4910 Y23.0630
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X5.4910 Y24.3630
G01 Z-1.7000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


